WINDOW_WIDTH = 960
WINDOW_HEIGHT = 540
WINDOW_SIZE = WINDOW_WIDTH, WINDOW_HEIGHT

SCALED_WINDOW_WIDTH = 1280
SCALED_WINDOW_HEIGHT = 720
SCALED_WINDOW_SIZE = SCALED_WINDOW_WIDTH, SCALED_WINDOW_HEIGHT

CAPTION = "Bubble Bee 2D"
FRAMERATE = 60

TILE_FLOOR = 0
TILE_WALL = 1

TILE_WIDTH = 48
TILE_HEIGHT = 48
TILE_SIZE = TILE_WIDTH, TILE_HEIGHT

WHITE = 255, 255, 255
BLACK = 0, 0, 0
BLUE = 0, 0, 255
RED = 255, 0, 0
GREEN = 0, 255, 0
GRAY = 128, 128, 128

GRID_WIDTH = 19
GRID_HEIGHT = 12
GRID_SIZE = GRID_WIDTH, GRID_HEIGHT
GRID_WIDTH_PIXELS = GRID_WIDTH * TILE_WIDTH
GRID_HEIGHT_PIXELS = GRID_HEIGHT * TILE_HEIGHT

ORIGIN = (WINDOW_WIDTH - GRID_WIDTH_PIXELS)//2, (WINDOW_HEIGHT - GRID_HEIGHT_PIXELS)//2
